# Generated by Django 4.1.3 on 2023-03-13 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Clubbing", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(name="account", options={},),
        migrations.RemoveField(model_name="account", name="date_joined",),
        migrations.RemoveField(model_name="account", name="first_name",),
        migrations.RemoveField(model_name="account", name="groups",),
        migrations.RemoveField(model_name="account", name="last_name",),
        migrations.RemoveField(model_name="account", name="user_permissions",),
    ]
