# Generated by Django 4.1.3 on 2023-03-13 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Clubbing", "0002_alter_account_options_remove_account_date_joined_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookmodel", old_name="event_id", new_name="event_id_id",
        ),
        migrations.RenameField(
            model_name="bookmodel", old_name="u_id", new_name="u_id_id",
        ),
        migrations.RenameField(
            model_name="empmodel", old_name="club_id", new_name="club_id_id",
        ),
        migrations.RenameField(
            model_name="eventmodel", old_name="club_id", new_name="club_id_id",
        ),
        migrations.RenameField(
            model_name="usermodel", old_name="club_id", new_name="club_id_id",
        ),
    ]
