# Generated by Django 4.1.3 on 2023-03-13 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Clubbing", "0003_rename_event_id_bookmodel_event_id_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usermodel", old_name="club_id_id", new_name="club_id",
        ),
    ]
