# Generated by Django 4.1.3 on 2023-03-13 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Clubbing", "0004_rename_club_id_id_usermodel_club_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="club_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Clubbing.clubmodel",
            ),
        ),
    ]
