# Generated by Django 4.1.3 on 2023-03-16 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Clubbing", "0005_alter_usermodel_club_id"),
    ]

    operations = [
        migrations.RemoveField(model_name="bookmodel", name="event_id_id",),
        migrations.RemoveField(model_name="bookmodel", name="u_id_id",),
        migrations.RemoveField(model_name="empmodel", name="club_id_id",),
        migrations.RemoveField(model_name="eventmodel", name="club_id_id",),
        migrations.AddField(
            model_name="bookmodel",
            name="event_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Clubbing.eventmodel",
            ),
        ),
        migrations.AddField(
            model_name="bookmodel",
            name="u_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Clubbing.usermodel",
            ),
        ),
        migrations.AddField(
            model_name="empmodel",
            name="club_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Clubbing.clubmodel",
            ),
        ),
        migrations.AddField(
            model_name="eventmodel",
            name="club_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Clubbing.clubmodel",
            ),
        ),
    ]
