# Generated by Django 4.2.3 on 2023-10-10 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Clubbing", "0007_delete_account_clubmodel_groups_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(name="clubmodel", table="Club",),
    ]
