# Generated by Django 4.2.3 on 2023-10-10 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Clubbing", "0008_alter_clubmodel_table"),
    ]

    operations = [
        migrations.AlterModelTable(name="clubmodel", table=None,),
    ]
