# Generated by Django 4.2.3 on 2023-10-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Clubbing", "0009_alter_clubmodel_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubmodel",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="clubmodel",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="clubmodel",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="clubmodel",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
